### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by JessicaYeh** [JessicaYeh/rom-exchange-web#19]
Create a Discord bot that will spit out for the specified item the current price on Global/SEA and the percent change over a week. Should also include a link to the item on romexchange.com. The URL would be something like https://www.romexchange.com/?q=mastela%20fruit&exact=true. Need to add support for the `exact` query parameter (already supported by the API)

**Comment by chklch** [comment]
Hey Jessica.   I spent some time yesterday doing this.  

https://github.com/chklch/RomExchangeBot

Feel free to use it and modify it for your own use.

**Comment by chklch** [comment]
Already done! It was a half day project for me yesterday.  I think it is still rough, but I can make changes to the bot to be publicly available.  

I've sent you an email with a link to the git hub repo.
