### ISSUE TITLE
Error importing app on test

### ISSUE THREAD

**Issue by murtinha** [JessicaYeh/rom-exchange-web#20]
Is this import correct?
![image](https://user-images.githubusercontent.com/17397678/52983965-29414880-33cc-11e9-8fdf-86092bed8b7b.png)

Its in ` app.test.tsx`. Shouldnt it be:
```
import App from './app';
```

The project only ran after I had changed it here

Forked it to try to implement the `Price change` filter

**Comment by JessicaYeh** [comment]
Yes you are correct :D I never actually ran the tests since there are currently no tests.. whoops

**Comment by murtinha** [comment]
I didnt run tests. The application broken on running `yarn start`
