### ISSUE TITLE
[Enhancement] Get only LATEST prices

### ISSUE THREAD

**Issue by rom-beans** [JessicaYeh/rom-exchange-web#29]
Currently, google scripts only allow up to a maximum of ~~2KB~~ 8KB per url fetch.

Would it be possible to strip down the information requested further to only latest price? Even if requesting for only a single item is exceeding the ~~2KB~~ 8KB limit.

EDIT: Up to 8KB, but is still not enough

**Comment by JessicaYeh** [comment]
Oh I didn't know that! I'll add a query parameter that lets you specify that you only want the latest price. It will still return things like the name and type, but it will strip out that big chunk of stats that is taking up too much data.

**Comment by JessicaYeh** [comment]
This has been added to the API. Please check the updated [API Docs](https://jessicayeh.github.io/rom-exchange-openapi/#operation/getItems) for info on how to use it (basically just add `slim=true` or `slim=1` to the query parameters)

**Comment by rom-beans** [comment]
Amazing! Thank you :)

One last thing though, can I still get the timestamp of the latest price? Just so we can check how old the data is. Once again, thank you :D

**Comment by JessicaYeh** [comment]
Just added a `latest_time` property next to the `latest` property

**Comment by rom-beans** [comment]
Amazing! That's all, thank you
