### ISSUE TITLE
Include item ID in the response

### ISSUE THREAD

**Issue by florobarotjr** [JessicaYeh/rom-exchange-web#32]
Would you be okay including the item id in the response? I would want to integrate it roexplorer.com which uses the item's id

**Comment by JessicaYeh** [comment]
Could you explain more on how you would use the item id? The item id is currently just an arbitrary unique number and is not used for lookup by the ROM Exchange API.

**Comment by florobarotjr** [comment]
Take https://roexplorer.com/item/52402 for example, `52402` being the item ID. I'm working under the assumption that it's RO-specific since it's the same ID used by ROGuard as well.

Essentially, I'd use your API to get the ID, scrape the Roexplorer for the mats required for me to craft an item, then call your api to populate the prices. I will then have a dashboard of all the mats that I need, along with the cost, without manually listing them one by one.

**Comment by JessicaYeh** [comment]
Oh I see. I currently don't have plans to add that item id to my database. It should be relatively straight forward to lookup the item id yourself by using their undocumented API though? Inspecting the browser network traffic shows a call to `https://search.roexplorer.com/explore/item/_msearch?` when you perform a search by name, and the response is a JSON that includes the item id of items it finds. Just find the item id of the item whose name matches your item name exactly.

**Comment by florobarotjr** [comment]
I'll try that! No worries, @JessicaYeh! Feel free to close this one! I appreciate all your work here :)
