### ISSUE TITLE
Be able to filter by item type

### ISSUE THREAD

**Issue by JessicaYeh** [JessicaYeh/rom-exchange-web#4]
Requires database update to fill in types in API response

**Comment by dbourdeveloper** [comment]
Amazing project btw. Wanted to make something like this, but wouldn't mind contributing since there's already some work done here.

How is the data being stored? Is it just a dump or is it on a RDBMS? I noticed https://www.romexchange.com/api/ just returns one large JSON back. Were you thinking of implementing a client side only filtering system to sort this dump?

**Comment by JessicaYeh** [comment]
Thanks! Looking forward to seeing your contributions!

Data is stored in a SQL database. The API supports a few query parameters, one of them is `type` and it expects a number. Today I actually just finished changing the data collection so that types can start to be collected, so most of the items should have a non-zero type now. Some might still be 0 if they didn't appear in the store today.

Here is the mapping for number -> type. Note that a few of the types will have 0 items, such as Scroll / Album (too many useless items to bother with tracking) and Holiday material and Costume, which I haven't seen any items appear in those categories.
```
1 Weapons
2 Off-hand
3 Armors
4 Garments
5 Footgears
6 Accessory
7 Blueprint
8 Potion / Effect
9 Refine
10 Scroll / Album
11 Material
12 Holiday material
13 Pet material
14 Premium
15 Costume
16 Head
17 Face
18 Back
19 Mouth
20 Tail
21 Weapon card
22 Off-hand card
23 Armor card
24 Garments card
25 Shoe card
26 Accessory card
27 Headwear card
```

For example, if I want to just see materials, I would use https://www.romexchange.com/api?type=11 for the endpoint.

**Comment by dbourdeveloper** [comment]
Just to clarify

Is the long URL a concern for a UX standpoint? If so, it doesn't appear to be an issue since we're keeping these URLs only for server calls unless a future intent is to have these URLs shareable and displayed on the client UI itself.

**Comment by JessicaYeh** [comment]
Yeah right now the user wouldn't see the URL anywhere unless they checked the network requests. But yeah definitely could have a shareable link in the future. The site URL already auto updates to include a ?q={search} if you search by name, and would be pretty easy to add the other parts like the server and range filter and the sorting type into there, but figured that would be kinda too cluttered. Would probably be better to have a share button that generates the full URL with every filtering and sorting option in the query params.

**Comment by dbourdeveloper** [comment]
Ah got it. I could see how the filtering attributes would be very long. Might be unavoidable. I'll see what I can whip up if you don't get to this first :)

**Comment by JessicaYeh** [comment]
Btw if you start working on it - be aware that the data that loads in the localhost version is going to be fake data loaded from just a static .json file instead of directly from the server. So it may be a bit difficult to test that the filtering actually works locally, but I'll help out in testing and stuff when we get to that point. The reason for the static .json is because I ran into some issues with CORS and couldn't get the backend script to allow cross-origin requests from any other location besides the domain itself. I'll keep trying to resolve it, but it might just be a restriction with the particular web host I'm on, and I feel like they are overriding my configuration.
