### ISSUE TITLE
Records more than 1 week

### ISSUE THREAD

**Issue by brandnewstring** [JessicaYeh/rom-exchange-web#47]
Can we have 1 month's or even 2 month's price record?
Because some game activities last for 1 month. Thank you!

**Comment by JessicaYeh** [comment]
This is already a feature, please check the Time Range filter in the settings.

![image](https://user-images.githubusercontent.com/3309218/58054027-e1db6d00-7b1e-11e9-8091-aff4af618276.png)

**Comment by brandnewstring** [comment]
Thx. Missed that.
